# Generated by Django 4.2 on 2026-05-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_contable', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movimientocontable',
            new_name='movimiento__sub_cue_381939_idx',
            old_name='movimiento__sub_cue_3a2c1f_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocontable',
            new_name='movimiento__modulo__5e5bbc_idx',
            old_name='movimiento__modulo__8b1d9e_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientocontable',
            new_name='movimiento__asiento_df7861_idx',
            old_name='movimiento__asiento_2f5a8c_idx',
        ),
    ]
