# Generated by Django 4.2 on 2026-02-01 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_preciocliente_historicalpreciocliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etiquetas', '0002_rename_created_by_etiqueta_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('precio_lay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('placa', models.CharField(max_length=20)),
                ('clindraje', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=4)),
                ('chasis', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria'), ('PAS', 'Pasaporte')], default='CC', max_length=20)),
                ('numero_documento', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('cotizador_estado', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('tramite_estado', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='0', max_length=1)),
                ('confirmacion_estado', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='0', max_length=1)),
                ('cargaro_estado', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizadores', to='clientes.cliente')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizadores', to='etiquetas.etiqueta')),
                ('precio_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizadores', to='clientes.preciocliente')),
            ],
            options={
                'verbose_name': 'Cotizador',
                'verbose_name_plural': 'Cotizadores',
                'db_table': 'cotizadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCotizadorPagos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('precio_lay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cotizador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cotizador.cotizador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cotizador Pago',
                'verbose_name_plural': 'historical Cotizador Pagos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCotizador',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('precio_lay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('placa', models.CharField(max_length=20)),
                ('clindraje', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=4)),
                ('chasis', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria'), ('PAS', 'Pasaporte')], default='CC', max_length=20)),
                ('numero_documento', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('cotizador_estado', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=1)),
                ('tramite_estado', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='0', max_length=1)),
                ('confirmacion_estado', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='0', max_length=1)),
                ('cargaro_estado', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo')], default='0', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('etiqueta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='etiquetas.etiqueta')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('precio_cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.preciocliente')),
            ],
            options={
                'verbose_name': 'historical Cotizador',
                'verbose_name_plural': 'historical Cotizadores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CotizadorPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_lay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cotizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cotizador.cotizador')),
            ],
            options={
                'verbose_name': 'Cotizador Pago',
                'verbose_name_plural': 'Cotizador Pagos',
                'db_table': 'cotizador_pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
