# Generated by Django 4.2 on 2026-02-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizador',
            old_name='cargaro_estado',
            new_name='cargar_pdf_estado',
        ),
        migrations.RenameField(
            model_name='historicalcotizador',
            old_name='cargaro_estado',
            new_name='cargar_pdf_estado',
        ),
    ]
