# Generated by Django 4.2 on 2026-01-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('contador', 'Contador'), ('cliente', 'Cliente')], default='admin', max_length=20),
        ),
    ]
