# Generated by Django 4.2 on 2026-01-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Administrador'), ('admin', 'Administrador'), ('auxiliar', 'Auxiliar'), ('vendedor', 'Vendedor'), ('contador', 'Contador'), ('cliente', 'Cliente')], default='admin', max_length=20),
        ),
    ]
