# Generated by Django 4.2 on 2026-03-04 20:36

from django.db import migrations


MODULES = [
    ('Dashboard', 'dashboard'),
    ('Usuarios', 'usuarios'),
    ('Clientes', 'clientes'),
    ('Etiquetas', 'etiquetas'),
    ('Tarjetas', 'tarjetas'),
    ('Recepción de pagos', 'recepcion_pagos'),
    ('Devoluciones', 'devoluciones'),
    ('Cargos no registrados', 'cargos_no_registrados'),
    ('Ajuste de saldo', 'ajuste_saldo'),
    ('Gastos', 'gastos'),
    ('Tarifario SOAT', 'tarifario_soat'),
    ('Reportes', 'reportes'),
    ('Configuración', 'configuracion'),
    ('Cotizador', 'cotizador'),
    ('Proveedores', 'proveedores'),
    ('Utilidad ocasional', 'utilidad_ocasional'),
]


def populate_modules(apps, schema_editor):
    Module = apps.get_model('users', 'Module')
    for name, code in MODULES:
        Module.objects.get_or_create(code=code, defaults={'name': name})


def reverse_populate(apps, schema_editor):
    Module = apps.get_model('users', 'Module')
    codes = [code for _, code in MODULES]
    Module.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_module_usermodulepermission_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_modules, reverse_populate),
    ]
