# Generated by Django 4.2 on 2026-06-12 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tramites', '0002_tramite_entidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPagoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, choices=[('previsora', 'Previsora'), ('mundial', 'Mundial')], default='', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('exitoso', 'Exitoso'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('url_pago', models.TextField(blank=True, default='')),
                ('correo_usado', models.CharField(blank=True, default='', max_length=255)),
                ('payload_enviado', models.JSONField(blank=True, null=True)),
                ('respuesta_cruda', models.JSONField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('task_id', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_pago_job', to='tramites.tramite')),
            ],
            options={
                'verbose_name': 'Job de link de pago',
                'verbose_name_plural': 'Jobs de link de pago',
                'db_table': 'tramites_link_pago_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLinkPagoJob',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, choices=[('previsora', 'Previsora'), ('mundial', 'Mundial')], default='', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('exitoso', 'Exitoso'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('url_pago', models.TextField(blank=True, default='')),
                ('correo_usado', models.CharField(blank=True, default='', max_length=255)),
                ('payload_enviado', models.JSONField(blank=True, null=True)),
                ('respuesta_cruda', models.JSONField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True, default='')),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('task_id', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tramites.tramite')),
            ],
            options={
                'verbose_name': 'historical Job de link de pago',
                'verbose_name_plural': 'historical Jobs de link de pago',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
