# Generated by Django 4.2 on 2026-06-16 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_proveedor_protegido'),
        ('tramites', '0003_linkpagojob_historicallinkpagojob'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltramite',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Proveedor asociado, derivado de la entidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor asociado, derivado de la entidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites', to='proveedores.proveedor'),
        ),
    ]
