# Generated by Django 4.2 on 2026-05-09 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalComputadorIP',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Alias o nombre identificador de la IP', max_length=100)),
                ('ip', models.GenericIPAddressField(help_text='Dirección IPv4 o IPv6')),
                ('puerto', models.PositiveIntegerField(blank=True, help_text='Puerto opcional (1-65535)', null=True)),
                ('protocolo', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', max_length=10)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=False, help_text='Si la IP está activa en el conmutador')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario que registró la IP', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical IP del conmutador',
                'verbose_name_plural': 'historical IPs del conmutador',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ComputadorIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Alias o nombre identificador de la IP', max_length=100)),
                ('ip', models.GenericIPAddressField(help_text='Dirección IPv4 o IPv6')),
                ('puerto', models.PositiveIntegerField(blank=True, help_text='Puerto opcional (1-65535)', null=True)),
                ('protocolo', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', max_length=10)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=False, help_text='Si la IP está activa en el conmutador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que registró la IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computador_ips_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP del conmutador',
                'verbose_name_plural': 'IPs del conmutador',
                'db_table': 'computador_ips',
                'ordering': ['-created_at'],
            },
        ),
    ]
