# Generated by Django 4.2 on 2026-05-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela_de_pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpasarelapago',
            name='observacion',
            field=models.TextField(blank=True, default='', help_text='Notas opcionales del usuario al confirmar el pago'),
        ),
        migrations.AddField(
            model_name='pasarelapago',
            name='observacion',
            field=models.TextField(blank=True, default='', help_text='Notas opcionales del usuario al confirmar el pago'),
        ),
    ]
