# Generated by Django 4.2 on 2026-05-05 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_historicaltarjeta_usuario_tarjeta_usuario'),
        ('pasarela_de_pago', '0002_historicalpasarelapago_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpasarelapago',
            name='tarjeta',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Tarjeta utilizada para el pago (seleccionada en el modal de timer)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tarjetas.tarjeta'),
        ),
        migrations.AddField(
            model_name='pasarelapago',
            name='tarjeta',
            field=models.ForeignKey(blank=True, help_text='Tarjeta utilizada para el pago (seleccionada en el modal de timer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasarela_pagos', to='tarjetas.tarjeta'),
        ),
    ]
