# Generated by Django 4.2 on 2026-06-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela_de_pago', '0004_add_pago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpasarelapago',
            name='entidad',
            field=models.CharField(blank=True, choices=[('MUNDIAL', 'Mundial'), ('PREVISORA', 'Previsora'), ('SOLIDARIA', 'Solidaria'), ('MANUAL', 'Manual')], default='', help_text='Aseguradora (snapshot del trámite)', max_length=20),
        ),
        migrations.AddField(
            model_name='pasarelapago',
            name='entidad',
            field=models.CharField(blank=True, choices=[('MUNDIAL', 'Mundial'), ('PREVISORA', 'Previsora'), ('SOLIDARIA', 'Solidaria'), ('MANUAL', 'Manual')], default='', help_text='Aseguradora (snapshot del trámite)', max_length=20),
        ),
    ]
