# Generated by Django 4.2 on 2026-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela_de_pago', '0005_historicalpasarelapago_entidad_pasarelapago_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpasarelapago',
            name='comprobante_pago',
            field=models.TextField(blank=True, help_text='Imagen del comprobante de pago; requerida para marcar el pago exitoso', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pasarelapago',
            name='comprobante_pago',
            field=models.FileField(blank=True, help_text='Imagen del comprobante de pago; requerida para marcar el pago exitoso', max_length=500, null=True, upload_to='pasarela_de_pago/comprobantes/'),
        ),
    ]
