# Generated by Django 4.2 on 2026-06-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela_de_pago', '0006_historicalpasarelapago_comprobante_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpasarelapago',
            name='comprobante_pago',
            field=models.URLField(blank=True, default='', help_text='URL del comprobante de pago en S3; requerida para marcar el pago exitoso', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pasarelapago',
            name='comprobante_pago',
            field=models.URLField(blank=True, default='', help_text='URL del comprobante de pago en S3; requerida para marcar el pago exitoso', max_length=1000),
        ),
    ]
