# Generated by Django 4.2 on 2026-06-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarela_de_pago', '0007_alter_historicalpasarelapago_comprobante_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpasarelapago',
            name='link_pago',
            field=models.URLField(blank=True, default='', help_text='Link de pago generado para el trámite (snapshot)', max_length=1000),
        ),
        migrations.AddField(
            model_name='pasarelapago',
            name='link_pago',
            field=models.URLField(blank=True, default='', help_text='Link de pago generado para el trámite (snapshot)', max_length=1000),
        ),
    ]
