# Generated by Django 4.2 on 2026-04-02 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_cliente_tipo_cliente_historicalcliente_tipo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(choices=[('SOAT', 'SOAT'), ('SOAT_ESPECIAL', 'SOAT Especial')], default='SOAT', max_length=20)),
                ('tipo_vehiculo', models.CharField(choices=[('USADO', 'Usado'), ('CERO_KM', 'Cero Kilómetros')], default='USADO', max_length=20)),
                ('es_propietario', models.BooleanField(default=True)),
                ('tipo_documento', models.CharField(choices=[('C', 'Cédula de Ciudadanía'), ('E', 'Cédula de Extranjería'), ('N', 'NIT'), ('P', 'Pasaporte'), ('T', 'Tarjeta de Identidad'), ('R', 'Registro Civil'), ('D', 'Documento de Identificación Extranjero'), ('S', 'Salvoconducto'), ('L', 'Licencia de Conducción'), ('PE', 'Permiso Especial de Permanencia (PEP)'), ('PT', 'Permiso por Protección Temporal (PPT)')], default='C', max_length=5)),
                ('numero_documento', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('clase', models.CharField(blank=True, max_length=100, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_carroceria', models.CharField(blank=True, max_length=100, null=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('num_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('num_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('linea', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=10, null=True)),
                ('cilindraje', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('organismo_transito', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_vehiculo', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_vehiculo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Vehículo',
                'verbose_name_plural': 'Registros de Vehículos',
                'db_table': 'base_de_datos_registro_vehiculo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistroVehiculo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_tramite', models.CharField(choices=[('SOAT', 'SOAT'), ('SOAT_ESPECIAL', 'SOAT Especial')], default='SOAT', max_length=20)),
                ('tipo_vehiculo', models.CharField(choices=[('USADO', 'Usado'), ('CERO_KM', 'Cero Kilómetros')], default='USADO', max_length=20)),
                ('es_propietario', models.BooleanField(default=True)),
                ('tipo_documento', models.CharField(choices=[('C', 'Cédula de Ciudadanía'), ('E', 'Cédula de Extranjería'), ('N', 'NIT'), ('P', 'Pasaporte'), ('T', 'Tarjeta de Identidad'), ('R', 'Registro Civil'), ('D', 'Documento de Identificación Extranjero'), ('S', 'Salvoconducto'), ('L', 'Licencia de Conducción'), ('PE', 'Permiso Especial de Permanencia (PEP)'), ('PT', 'Permiso por Protección Temporal (PPT)')], default='C', max_length=5)),
                ('numero_documento', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('clase', models.CharField(blank=True, max_length=100, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_carroceria', models.CharField(blank=True, max_length=100, null=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('num_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('num_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('linea', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=10, null=True)),
                ('cilindraje', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('organismo_transito', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Registro de Vehículo',
                'verbose_name_plural': 'historical Registros de Vehículos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
