# Generated by Django 4.2 on 2026-05-08 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarjetas', '0002_historicaltarjeta_usuario_tarjeta_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCuatroPorMil',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('recepcion_pago', 'Recepción de pagos'), ('devoluciones', 'Devoluciones'), ('gastos', 'Gastos'), ('cargos_no_registrados', 'Cargos no registrados'), ('utilidad_ocasional', 'Utilidad ocasional'), ('pasarela_de_pago', 'Pasarela de pago'), ('finalizados_tramites', 'Trámites finalizados')], help_text='Módulo origen del 4x1000', max_length=50)),
                ('registro_id', models.PositiveIntegerField(help_text='ID del registro en el módulo origen')),
                ('valor', models.DecimalField(decimal_places=2, default=0, help_text='Valor del 4x1000', max_digits=10)),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, help_text='Valor base sobre el que se calculó', max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha de la transacción origen', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tarjeta', models.ForeignKey(blank=True, db_constraint=False, help_text='Tarjeta asociada (cuando aplique)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tarjetas.tarjeta')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario que registró el 4x1000', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cuatro por mil',
                'verbose_name_plural': 'historical Cuatros por mil',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CuatroPorMil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('recepcion_pago', 'Recepción de pagos'), ('devoluciones', 'Devoluciones'), ('gastos', 'Gastos'), ('cargos_no_registrados', 'Cargos no registrados'), ('utilidad_ocasional', 'Utilidad ocasional'), ('pasarela_de_pago', 'Pasarela de pago'), ('finalizados_tramites', 'Trámites finalizados')], help_text='Módulo origen del 4x1000', max_length=50)),
                ('registro_id', models.PositiveIntegerField(help_text='ID del registro en el módulo origen')),
                ('valor', models.DecimalField(decimal_places=2, default=0, help_text='Valor del 4x1000', max_digits=10)),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, help_text='Valor base sobre el que se calculó', max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha de la transacción origen', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tarjeta', models.ForeignKey(blank=True, help_text='Tarjeta asociada (cuando aplique)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuatro_por_mil_registros', to='tarjetas.tarjeta')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró el 4x1000', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuatro_por_mil_registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuatro por mil',
                'verbose_name_plural': 'Cuatros por mil',
                'db_table': 'cuatro_por_mil',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cuatropormil',
            index=models.Index(fields=['modulo', 'registro_id'], name='cuatro_por__modulo_d7937a_idx'),
        ),
    ]
