# Generated by Django 4.2 on 2026-05-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuatro_por_mil', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cuatropormil',
            constraint=models.UniqueConstraint(fields=('modulo', 'registro_id'), name='uniq_cuatro_por_mil_origen'),
        ),
    ]
