# Generated by Django 4.2 on 2026-06-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_cuentas', '0001_initial'),
        ('cuatro_por_mil', '0004_remove_cuatropormil_sub_cuenta_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuatropormil',
            name='sub_cuenta',
            field=models.ForeignKey(blank=True, help_text='Sub-cuenta contable de debito asociada al registro (opcional: el espejo se sincroniza por signal y no postea asiento)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuatro_por_mil_registros', to='sub_cuentas.subcuenta'),
        ),
        migrations.AlterField(
            model_name='historicalcuatropormil',
            name='sub_cuenta',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Sub-cuenta contable de debito asociada al registro (opcional: el espejo se sincroniza por signal y no postea asiento)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sub_cuentas.subcuenta'),
        ),
    ]
