# Generated by Django 4.2 on 2026-06-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuatro_por_mil', '0005_alter_cuatropormil_sub_cuenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuatropormil',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='cuatropormil',
            name='debito',
        ),
        migrations.RemoveField(
            model_name='cuatropormil',
            name='sub_cuenta',
        ),
        migrations.RemoveField(
            model_name='historicalcuatropormil',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='historicalcuatropormil',
            name='debito',
        ),
        migrations.RemoveField(
            model_name='historicalcuatropormil',
            name='sub_cuenta',
        ),
    ]
