# Generated by Django 4.2 on 2026-06-04 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuatro_por_mil', '0006_remove_cuatropormil_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuatropormil',
            name='asiento_id',
            field=models.UUIDField(blank=True, default=None, editable=False, help_text='UUID del asiento contable activo en MovimientoContable (null si aun no se registro o fue revertido)', null=True),
        ),
        migrations.AddField(
            model_name='historicalcuatropormil',
            name='asiento_id',
            field=models.UUIDField(blank=True, default=None, editable=False, help_text='UUID del asiento contable activo en MovimientoContable (null si aun no se registro o fue revertido)', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalCuatroPorMilConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sub_cuenta_debito', models.ForeignKey(blank=True, db_constraint=False, help_text='Sub-cuenta de debito por defecto para los asientos de 4x1000.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sub_cuentas.subcuenta')),
            ],
            options={
                'verbose_name': 'historical Configuracion Cuatro por mil',
                'verbose_name_plural': 'historical Configuracion Cuatro por mil',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CuatroPorMilConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_cuenta_debito', models.ForeignKey(blank=True, help_text='Sub-cuenta de debito por defecto para los asientos de 4x1000.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuatro_por_mil_config_debito', to='sub_cuentas.subcuenta')),
            ],
            options={
                'verbose_name': 'Configuracion Cuatro por mil',
                'verbose_name_plural': 'Configuracion Cuatro por mil',
                'db_table': 'cuatro_por_mil_config',
            },
        ),
    ]
