# Generated by Django 4.2 on 2026-02-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecepcionpago',
            name='fecha_recepcion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='recepcionpago',
            name='fecha_recepcion',
            field=models.DateTimeField(),
        ),
    ]
