# Generated by Django 4.2 on 2026-02-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_pago', '0002_alter_historicalrecepcionpago_fecha_recepcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrecepcionpago',
            old_name='fecha_recepcion',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='recepcionpago',
            old_name='fecha_recepcion',
            new_name='fecha',
        ),
    ]
