# Generated by Django 4.2 on 2026-02-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion_pago', '0003_rename_fecha_recepcion_historicalrecepcionpago_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecepcionpago',
            name='cuatro_por_mil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalrecepcionpago',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recepcionpago',
            name='cuatro_por_mil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recepcionpago',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
