# Generated by Django 4.2 on 2026-05-20 13:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], help_text='Tipo de cuenta contable', max_length=20)),
                ('codigo_puc', models.CharField(help_text='Código PUC numérico de 4 dígitos (único, ingreso manual)', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='El Código PUC debe ser numérico de 4 dígitos.', regex='^\\d{4}$')])),
                ('nombre_cuenta', models.CharField(help_text='Nombre alfanumérico de la cuenta', max_length=200)),
                ('acumulado', models.CharField(choices=[('debito_credito', 'Débito (-) Crédito'), ('credito_debito', 'Crédito (-) Débito')], help_text='Naturaleza acumulada de la cuenta', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_de_cuentas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta del PUC',
                'verbose_name_plural': 'Plan de cuentas',
                'db_table': 'plan_de_cuentas',
                'ordering': ['codigo_puc'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlanDeCuentas',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], help_text='Tipo de cuenta contable', max_length=20)),
                ('codigo_puc', models.CharField(db_index=True, help_text='Código PUC numérico de 4 dígitos (único, ingreso manual)', max_length=4, validators=[django.core.validators.RegexValidator(message='El Código PUC debe ser numérico de 4 dígitos.', regex='^\\d{4}$')])),
                ('nombre_cuenta', models.CharField(help_text='Nombre alfanumérico de la cuenta', max_length=200)),
                ('acumulado', models.CharField(choices=[('debito_credito', 'Débito (-) Crédito'), ('credito_debito', 'Crédito (-) Débito')], help_text='Naturaleza acumulada de la cuenta', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cuenta del PUC',
                'verbose_name_plural': 'historical Plan de cuentas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
