# Generated by Django 4.2 on 2026-05-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalizados_tramites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltramitefinalizado',
            name='cuatro_por_mil_valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshot del 4x1000 calculado al confirmar el pago', max_digits=12),
        ),
        migrations.AddField(
            model_name='tramitefinalizado',
            name='cuatro_por_mil_valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshot del 4x1000 calculado al confirmar el pago', max_digits=12),
        ),
    ]
