# Generated by Django 4.2 on 2026-05-06 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finalizados_tramites.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalizados_tramites', '0002_historicaltramitefinalizado_cuatro_por_mil_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramiteFinalizadoPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to=finalizados_tramites.models._pdf_upload_path)),
                ('nombre_original', models.CharField(help_text='Nombre del archivo tal como lo subió el usuario', max_length=255)),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción libre del documento (editable)', max_length=255)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('finalizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='finalizados_tramites.tramitefinalizado')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalizados_pdfs_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF de trámite finalizado',
                'verbose_name_plural': 'PDFs de trámites finalizados',
                'db_table': 'tramites_finalizados_pdfs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTramiteFinalizadoPdf',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('archivo', models.TextField(max_length=500)),
                ('nombre_original', models.CharField(help_text='Nombre del archivo tal como lo subió el usuario', max_length=255)),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción libre del documento (editable)', max_length=255)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('finalizado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finalizados_tramites.tramitefinalizado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical PDF de trámite finalizado',
                'verbose_name_plural': 'historical PDFs de trámites finalizados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
