# Generated by Django 4.2 on 2026-06-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalizados_tramites', '0003_tramitefinalizadopdf_historicaltramitefinalizadopdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltramitefinalizado',
            name='entidad',
            field=models.CharField(blank=True, choices=[('MUNDIAL', 'Mundial'), ('PREVISORA', 'Previsora'), ('SOLIDARIA', 'Solidaria'), ('MANUAL', 'Manual')], default='', help_text='Aseguradora (snapshot)', max_length=20),
        ),
        migrations.AddField(
            model_name='tramitefinalizado',
            name='entidad',
            field=models.CharField(blank=True, choices=[('MUNDIAL', 'Mundial'), ('PREVISORA', 'Previsora'), ('SOLIDARIA', 'Solidaria'), ('MANUAL', 'Manual')], default='', help_text='Aseguradora (snapshot)', max_length=20),
        ),
    ]
