# Generated by Django 4.2 on 2026-06-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalizados_tramites', '0004_historicaltramitefinalizado_entidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltramitefinalizado',
            name='comprobante_pago',
            field=models.URLField(blank=True, default='', help_text='URL del comprobante de pago en S3 (snapshot de la pasarela)', max_length=1000),
        ),
        migrations.AddField(
            model_name='tramitefinalizado',
            name='comprobante_pago',
            field=models.URLField(blank=True, default='', help_text='URL del comprobante de pago en S3 (snapshot de la pasarela)', max_length=1000),
        ),
    ]
