# Generated by Django 4.2 on 2026-06-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalizados_tramites', '0006_historicaltramitefinalizado_link_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltramitefinalizado',
            name='asiento_comision_id',
            field=models.UUIDField(blank=True, help_text='UUID del asiento de comisión SOAT', null=True),
        ),
        migrations.AddField(
            model_name='historicaltramitefinalizado',
            name='asiento_emision_id',
            field=models.UUIDField(blank=True, help_text='UUID del asiento de emisión SOAT', null=True),
        ),
        migrations.AddField(
            model_name='tramitefinalizado',
            name='asiento_comision_id',
            field=models.UUIDField(blank=True, help_text='UUID del asiento de comisión SOAT', null=True),
        ),
        migrations.AddField(
            model_name='tramitefinalizado',
            name='asiento_emision_id',
            field=models.UUIDField(blank=True, help_text='UUID del asiento de emisión SOAT', null=True),
        ),
    ]
