# Generated by Django 4.2 on 2026-02-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicaletiqueta',
            old_name='created_by',
            new_name='user',
        ),
    ]
