# Generated by Django 4.2 on 2026-06-04 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_cuentas', '0001_initial'),
        ('utilidad_ocasional', '0004_add_utilidadocasional_asiento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilidadOcasionalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_cuenta_negativa', models.ForeignKey(blank=True, help_text='Sub-cuenta contracuenta para utilidades con valor negativo (perdida).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilidad_ocasional_config_negativa', to='sub_cuentas.subcuenta')),
                ('sub_cuenta_positiva', models.ForeignKey(blank=True, help_text='Sub-cuenta contracuenta para utilidades con valor positivo (ganancia).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilidad_ocasional_config_positiva', to='sub_cuentas.subcuenta')),
            ],
            options={
                'verbose_name': 'Configuracion Utilidad Ocasional',
                'verbose_name_plural': 'Configuracion Utilidad Ocasional',
                'db_table': 'utilidad_ocasional_config',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUtilidadOcasionalConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sub_cuenta_negativa', models.ForeignKey(blank=True, db_constraint=False, help_text='Sub-cuenta contracuenta para utilidades con valor negativo (perdida).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sub_cuentas.subcuenta')),
                ('sub_cuenta_positiva', models.ForeignKey(blank=True, db_constraint=False, help_text='Sub-cuenta contracuenta para utilidades con valor positivo (ganancia).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sub_cuentas.subcuenta')),
            ],
            options={
                'verbose_name': 'historical Configuracion Utilidad Ocasional',
                'verbose_name_plural': 'historical Configuracion Utilidad Ocasional',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
