# Generated by Django 4.2 on 2026-06-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidad_ocasional', '0005_utilidadocasionalconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalutilidadocasional',
            name='tipo',
            field=models.CharField(choices=[('ganancia', 'Ganancia'), ('perdida', 'Pérdida')], default='ganancia', help_text='Ganancia o perdida; define la sub-cuenta y la direccion del asiento.', max_length=10),
        ),
        migrations.AddField(
            model_name='utilidadocasional',
            name='tipo',
            field=models.CharField(choices=[('ganancia', 'Ganancia'), ('perdida', 'Pérdida')], default='ganancia', help_text='Ganancia o perdida; define la sub-cuenta y la direccion del asiento.', max_length=10),
        ),
    ]
