# Generated by Django 4.2 on 2026-02-01 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltarjeta',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario asociado a la tarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario asociado a la tarjeta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas', to=settings.AUTH_USER_MODEL),
        ),
    ]
