# Generated by Django 4.2 on 2026-03-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_preciocliente_historicalpreciocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('cda', 'CDA'), ('concesionario', 'Concesionario'), ('particular', 'Particular'), ('punto_aliado', 'Punto aliado')], default='particular', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('cda', 'CDA'), ('concesionario', 'Concesionario'), ('particular', 'Particular'), ('punto_aliado', 'Punto aliado')], default='particular', max_length=20),
        ),
    ]
