# Generated by Django 4.2 on 2026-04-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_tipo_cliente_historicalcliente_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
