# Generated by Django 4.2 on 2026-04-02 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del endpoint', max_length=100)),
                ('codigo', models.CharField(help_text='Código interno único (ej: RUNT_VEHICULO)', max_length=50, unique=True)),
                ('url_base', models.CharField(help_text='URL base del endpoint externo', max_length=500)),
                ('metodo_http', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del propósito del endpoint', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si el endpoint está habilitado para uso')),
                ('timeout', models.IntegerField(default=30, help_text='Timeout en segundos para la petición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Endpoint Externo',
                'verbose_name_plural': 'Endpoints Externos',
                'db_table': 'api_app_external_endpoints',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalExternalEndpoint',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del endpoint', max_length=100)),
                ('codigo', models.CharField(db_index=True, help_text='Código interno único (ej: RUNT_VEHICULO)', max_length=50)),
                ('url_base', models.CharField(help_text='URL base del endpoint externo', max_length=500)),
                ('metodo_http', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del propósito del endpoint', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si el endpoint está habilitado para uso')),
                ('timeout', models.IntegerField(default=30, help_text='Timeout en segundos para la petición')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Endpoint Externo',
                'verbose_name_plural': 'historical Endpoints Externos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
