# Generated by Django 4.2 on 2026-05-20 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_de_cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='ID manual único: 3 letras mayúsculas + 3 dígitos (ej: ABC123)', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='El ID debe ser 3 letras mayúsculas seguidas de 3 dígitos (ej: ABC123).', regex='^[A-Z]{3}\\d{3}$')])),
                ('nombre_sub_cuenta', models.CharField(help_text='Nombre alfanumérico de la sub-cuenta (ej: BANCOLCP)', max_length=200)),
                ('debito', models.DecimalField(decimal_places=2, default=0, help_text='Movimiento débito', max_digits=15)),
                ('credito', models.DecimalField(decimal_places=2, default=0, help_text='Movimiento crédito', max_digits=15)),
                ('acumulado', models.DecimalField(decimal_places=2, default=0, help_text='Saldo acumulado de la sub-cuenta', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(help_text='Cuenta del PUC asociada (Plan de cuentas)', on_delete=django.db.models.deletion.PROTECT, related_name='sub_cuentas', to='plan_de_cuentas.plandecuentas')),
                ('user', models.ForeignKey(help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_cuentas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub-cuenta',
                'verbose_name_plural': 'Sub-cuentas',
                'db_table': 'sub_cuentas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubCuenta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='ID manual único: 3 letras mayúsculas + 3 dígitos (ej: ABC123)', max_length=6, validators=[django.core.validators.RegexValidator(message='El ID debe ser 3 letras mayúsculas seguidas de 3 dígitos (ej: ABC123).', regex='^[A-Z]{3}\\d{3}$')])),
                ('nombre_sub_cuenta', models.CharField(help_text='Nombre alfanumérico de la sub-cuenta (ej: BANCOLCP)', max_length=200)),
                ('debito', models.DecimalField(decimal_places=2, default=0, help_text='Movimiento débito', max_digits=15)),
                ('credito', models.DecimalField(decimal_places=2, default=0, help_text='Movimiento crédito', max_digits=15)),
                ('acumulado', models.DecimalField(decimal_places=2, default=0, help_text='Saldo acumulado de la sub-cuenta', max_digits=15)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cuenta', models.ForeignKey(blank=True, db_constraint=False, help_text='Cuenta del PUC asociada (Plan de cuentas)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plan_de_cuentas.plandecuentas')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sub-cuenta',
                'verbose_name_plural': 'historical Sub-cuentas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
