# Generated by Django 4.2 on 2026-05-31 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_cuentas', '0001_initial'),
        ('devoluciones', '0004_remove_devolucion_sub_cuenta_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldevolucion',
            name='sub_cuenta',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Sub-cuenta contable de debito asociada al registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sub_cuentas.subcuenta'),
        ),
    ]
