# Generated by Django 4.2 on 2026-05-31 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_categoria', '0002_add_debito_credito_sub_cuenta'),
        ('gastos', '0003_add_debito_credito_sub_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalgastorelacion',
            name='gasto',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Categoría asociada al gasto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gastos_categoria.gastocategoria'),
        ),
    ]
