# Generated by Django 4.2 on 2026-05-09 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finalizados_tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUtilidad',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha del trámite (snapshot de pago_confirmado_at)')),
                ('placa', models.CharField(blank=True, default='', max_length=20)),
                ('comision_proveedor', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot de la comisión (TramiteFinalizado.comision)', max_digits=10, null=True)),
                ('cilindraje', models.CharField(blank=True, default='', max_length=10)),
                ('modelo', models.CharField(blank=True, default='', max_length=4)),
                ('chasis', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tramite_finalizado', models.ForeignKey(blank=True, db_constraint=False, help_text='Trámite finalizado origen del registro de utilidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finalizados_tramites.tramitefinalizado')),
            ],
            options={
                'verbose_name': 'historical Utilidad',
                'verbose_name_plural': 'historical Utilidades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Utilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha del trámite (snapshot de pago_confirmado_at)')),
                ('placa', models.CharField(blank=True, default='', max_length=20)),
                ('comision_proveedor', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot de la comisión (TramiteFinalizado.comision)', max_digits=10, null=True)),
                ('cilindraje', models.CharField(blank=True, default='', max_length=10)),
                ('modelo', models.CharField(blank=True, default='', max_length=4)),
                ('chasis', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tramite_finalizado', models.OneToOneField(blank=True, help_text='Trámite finalizado origen del registro de utilidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilidad', to='finalizados_tramites.tramitefinalizado')),
            ],
            options={
                'verbose_name': 'Utilidad',
                'verbose_name_plural': 'Utilidades',
                'db_table': 'utilidades',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
